name: test
on:
  pull_request:
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - uses: pnpm/action-setup@v4
        with:
          version: 10.24.0
          run_install: false

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: install pnpm deps
        run: pnpm install --frozen-lockfile

      - name: frontend tests
        run: pnpm test:run

      - name: rust tests
        run: cargo test --manifest-path src-tauri/Cargo.toml
